library(shiny)
library(bs4Dash)
library(DT)
library(shinycssloaders)
library(vroom)
library(ggplot2)
library(plotly)
library(shinyWidgets)
library(dplyr)
library(tidyr)
library(rlang)
library(tidyverse)
library(shinyalert)
library(colourpicker)
library(readxl)
library(readODS)
library(DMwR2)
library(scales)
require(showtext)

# 載入中文字體
showtext_auto()
font_add('msjh', './msjh.ttc')